-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{
		["0005"] = {



										{
										pe_fixture_id = "", density = 1, friction = 0, bounce = 0,
										filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
										radius = 32.001
										}


		},
		["0006"] = {



										{
										pe_fixture_id = "", density = 1, friction = 0, bounce = 0,
										filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
										radius = 64.002
										}


		},

		["0007"] = {



                    {
                    pe_fixture_id = "", density = 1, friction = 0, bounce = 0,
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 128.004
                    }


		}

	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end

	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end

	return physics;
end

return M
